PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS tenants (id TEXT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS territories (id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL, name TEXT NOT NULL, slug TEXT NOT NULL, city TEXT DEFAULT 'Douala');
CREATE TABLE IF NOT EXISTS shops (id TEXT PRIMARY KEY, tenant_id TEXT DEFAULT 'default', name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, kwat TEXT NOT NULL, whatsapp TEXT NOT NULL, category TEXT, logo_r2_key TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, tenant_id TEXT DEFAULT 'default', shop_id TEXT, name TEXT NOT NULL, price_xaf INTEGER DEFAULT 0, kwat TEXT, category TEXT);
CREATE TABLE IF NOT EXISTS ad_slots (id TEXT PRIMARY KEY, tenant_id TEXT DEFAULT 'default', slot_type TEXT CHECK(slot_type IN ('FEATURED_TOP','CATEGORY_TOP','COMPETITOR_TAKEOVER','GEO_PUSH')) NOT NULL, kwat_target TEXT, budget_total INTEGER DEFAULT 0, whatsapp_clicks INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS ad_boosters (id TEXT PRIMARY KEY, merchant_id TEXT NOT NULL, amount_xaf INTEGER NOT NULL, ad_spend_target INTEGER NOT NULL, platform_fee_xaf INTEGER NOT NULL, fx_buffer_applied INTEGER DEFAULT 0, momo_payment_reference TEXT, meta_campaign_id TEXT, deployment_status TEXT CHECK(deployment_status IN ('PENDING_COLLECTION','PAID_MANUAL_QUEUE','CAMPAIGN_LIVE','FAILED')) DEFAULT 'PENDING_COLLECTION');
INSERT OR IGNORE INTO tenants (id, name) VALUES ('default','quick.cm');
INSERT OR IGNORE INTO territories (id, tenant_id, name, slug, city) VALUES ('akwa','default','Akwa','akwa','Douala'),('bonapriso','default','Bonapriso','bonapriso','Douala'),('bonaberi','default','Bonabéri','bonaberi','Douala'),('bepanda','default','Bepanda','bepanda','Douala'),('deido','default','Deido','deido','Douala'),('bonamoussadi','default','Bonamoussadi','bonamoussadi','Douala'),('bastos','default','Bastos','bastos','Yaoundé'),('biyem-assi','default','Biyem-Assi','biyem-assi','Yaoundé');
