name = "quick-cm"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".svelte-kit/cloudflare"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "quickcm-db"
database_id = "35e5601a-3c72-4ea5-b058-d8859cebd4a1"

[[kv_namespaces]]
binding = "CACHE"
id = "ccc2faafc57641dba1f184c29cb86137"
preview_id = "ccc2faafc57641dba1f184c29cb86137"

[[r2_buckets]]
binding = "R2"
bucket_name = "quickcm-images"

[env.production]
name = "quick-cm-prod"
routes = [
  { pattern = "quick.cm/*", zone_name = "quick.cm" },
  { pattern = "*.quick.cm/*", zone_name = "quick.cm" }
]

[env.production.vars]
PUBLIC_APP_URL = "https://quick.cm"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "ccc2faafc57641dba1f184c29cb86137"
preview_id = "ccc2faafc57641dba1f184c29cb86137"

[[env.production.d1_databases]]
binding = "DB"
database_name = "quickcm-db"
database_id = "35e5601a-3c72-4ea5-b058-d8859cebd4a1"

[[env.production.r2_buckets]]
binding = "R2"
bucket_name = "quickcm-images"

